version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/truck
    command: npm run dev
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
    depends_on:
      - backend
    command: npm run dev
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  mongo_data:
